# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy the custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 5000
EXPOSE 5010

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
